### PR TITLE
213 fix merit shifting

### LINKED ISSUE #213: Merit descriptions/specifications sometimes shift up one
Possibly an issue with some merits not using all the fields?? Whatever it is it's probably an issue with my garbage javascript

### PR DESCRIPTION
**Pull request by cmho**
Closes #213.

### CODE REVIEW

File: app/controllers/characters_controller.rb [hunk 1]
```diff
@@ -102,7 +102,7 @@ def edit
 	def update
 		@character = Character.find_by_id(params[:character][:id])
 		prevstatus = @character.status
-		puts params[:character][:character_has_flaws_attributes]
+		puts params[:character][:character_has_merits_attributes]
```
Comment (sublimemarch) [inline app/controllers/characters_controller.rb]: Remove this debugging statement.

**Comment by sublimemarch** [comment]
👍
